sprites: sprites-comic sprites-papyrus sprites-courier

sprites-comic:
	python3 genfont.py "Comic Sans MS" 72 comic

sprites-papyrus:
	python3 genfont.py "Papyrus" 72 papyrus

sprites-courier:
	python3 genfont.py "Courier New Bold" 72 courier

.PHONY: sprites sprites-comic sprites-papyrus sprites-courier
